services:
  ai-hub:
    build: .
    ports:
      - "${AI_HUB_PORT:-3001}:${AI_HUB_INTERNAL_PORT:-3000}"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-hub.rule=Host(`${TRAEFIK_HOST:-ai-learning-hub.localhost}`)"
      - "traefik.http.routers.ai-hub.entrypoints=web"
      - "traefik.http.services.ai-hub.loadbalancer.server.port=${AI_HUB_INTERNAL_PORT:-3000}"
      - "traefik.docker.network=traefik"
