services:
  ai-hub:
    build: .
    ports:
      - "3001:3000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-hub.rule=Host(`ai-learning-hub.localhost`)"
      - "traefik.http.routers.ai-hub.entrypoints=web"
      - "traefik.http.services.ai-hub.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
