services:
  ai-hub:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - web-proxy

networks:
  web-proxy:
    driver: bridge
