services:
  ai-hub:
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=ghcr.io/delorenj/ai-hub:buildcache
      cache_to:
        - type=registry,ref=ghcr.io/delorenj/ai-hub:buildcache,mode=max
    ports:
      - "${AI_HUB_PORT:-3001}:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CONTENT_PATH=/app/content
    volumes:
      - ./content:/app/content
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-hub.rule=Host(`hub.triumphbox.dev`)"
      - "traefik.http.routers.ai-hub.entrypoints=websecure"
      - "traefik.http.routers.ai-hub.tls.certresolver=letsencrypt"
      - "traefik.http.services.ai-hub.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
