[tools]
node = "20"

[tasks.dev]
description = "Start development server"
run = "npm run dev"

[tasks.build]
description = "Build for production"
run = "npm run build"

[tasks.start]
description = "Start production server"
run = "npm run start"

[tasks.lint]
description = "Run ESLint"
run = "npm run lint"

[tasks.typecheck]
description = "Run TypeScript type checking"
run = "npx tsc --noEmit"

[tasks.test]
description = "Run tests"
run = "npm test"

[tasks.docker-build]
description = "Build Docker image"
run = "docker compose build"

[tasks.docker-up]
description = "Start Docker containers"
run = "docker compose up -d"

[tasks.docker-down]
description = "Stop Docker containers"
run = "docker compose down"

[tasks.deploy]
description = "Deploy to production"
run = "./scripts/deploy-simple.sh"

[tasks.health-check]
description = "Check deployment health"
run = "./scripts/health-check.sh"

# Environment variables are set per task
# NODE_ENV will be set automatically by Next.js